#服务服务
server:
  port : 8083
  servlet:
    context-path: /cas-client

#服务名称配置
spring:
  application:
    name: cas-client

#服务日志配置
logging:
  path: ./logs
  level:
    root : info
    org.jasig : debug



# SSO 配置
cas:
  service:
    login: http://172.23.5.160:50080/sso/login
    logout: http://172.23.5.160:50080/sso/logout
  url:
    prefix: http://172.23.5.160:50080/sso
app:
  service:
    security: http://localhost:8081/cas-client/login/cas
    home: http://localhost:8081/cas-client

um:
  rmi:
    service:
      SecurityService:
        url: http://172.23.5.160:50080/console-api/remoting/SecurityService
